version: '3.3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper

    kafka-node-1:
        image: wurstmeister/kafka
        container_name: kafka-node-1
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    mysql-node-1:
        image: mysql
        container_name: mysql-node-1
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 3.14Oneer